name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'

    - name: Install Frontend Dependencies
      run: npm install

    - name: Install Backend Dependencies
      run: |
        cd backend
        npm install
        npx prisma generate

    - name: Lint All
      run: npm run lint

    - name: Build Frontend
      run: npm run build

    - name: Build Backend
      run: |
        cd backend
        npx tsc
